baseURL = 'https://moematsuda-ai.github.io/'
languageCode = 'ja-jp'
title = "'Moais blog"
theme = "hugo-theme-relearn"
publishDir = "docs"
buildDraft = false

[params]
  themeVariant = ["relearn-dark", "relearn-light", "green", "black", "blue", "learn"]
  ordersectionsby = "weight"
  showVisitedLinks = true

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"] 
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[Languages]
[Languages.en]
landingPageName = "<i class='fas fa-home'></i> Home"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/MoeMatsuda-ai/MoeMatsuda-ai.github.io"
weight = 50

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 70
